"""Comodines de la hoja 3 (assets/fuente/hoja_comodines_3.webp): 13 columnas x 4 filas.

Mismo formato que tools/comodines.py; el orden es el de la hoja, fila a fila.
"""
from comodines import (ACTUAL_C, ACTUAL_M, ACTUAL_X, CHIPS, MULT, PALO, PROB, XMULT,
                       J, crear, mano, palo, rango, retenida)

COMODINES = [
    # ---- Fila 1 ----
    J("bufon_azur", "Bufón Azur", 1, 3,
      [CHIPS % 1 + "; el {C:attention}doble{} en la", "primera mano de la ronda"], {"chips": 50}, ["chips"],
      "KAS.dyn(function(card, context, e) return { chips = KAS.first_hand() and e.chips * 2 or e.chips } end)"),
    J("bufoncillo", "Bufoncillo", 1, 4,
      [MULT % 1 + " por cada carta de valor", "{C:attention}5 o menos{} puntuada"], {"mult": 3}, ["mult"],
      "KAS.dyn(function(card, context, e) local n = KAS.contar(context.scoring_hand, KAS.rank(2, 3, 4, 5)) "
      "if n > 0 then return { mult = e.mult * n } end end)"),
    J("gran_bufon", "Gran Bufón", 1, 5,
      [MULT % 1 + " por cada", "carta puntuada"], {"mult": 3}, ["mult"],
      "KAS.dyn(function(card, context, e) return { mult = e.mult * #context.scoring_hand } end)"),
    J("bufon_morado", "Bufón Morado", 2, 7,
      ["Gana " + XMULT % 1 + " cada vez", "que juegas una {C:attention}Pareja{}", ACTUAL_X % 2],
      {"gain": 0.1, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = KAS.T.hand_type('Pair') }"),
    J("calavera_espadas", "Calavera de Espadas", 2, 6,
      ["Cada carta de " + PALO["Spades"] + " puntuada", "tiene " + PROB % (1, 2), "de dar " + XMULT % 3],
      {"odds": 2, "xmult": 1.5}, ["prob", "odds", "xmult"],
      'KAS.per_card(KAS.suit("Spades"), "kas_calavera_espadas")'),
    retenida("bufon_bosque", "Bufón del Bosque", 1, 4, 'KAS.suit("Clubs")',
             "carta de " + PALO["Clubs"], "mult", 3),
    J("gato_esmeralda", "Gato Esmeralda", 2, 7,
      ["Reactiva cada carta", "de " + PALO["Clubs"] + " puntuada"], {"reps": 1}, [],
      'KAS.retrigger(KAS.suit("Clubs"))'),
    J("simio_fantasma", "Simio Fantasma", 1, 5,
      [CHIPS % 1 + " por cada comodín", "{C:green}Poco común{} o mejor que tengas"], {"chips": 25}, ["chips"],
      "KAS.dyn(function(card, context, e) local n = 0 for _, j in ipairs(G.jokers.cards) do "
      "if j.config.center.rarity ~= 1 then n = n + 1 end end if n > 0 then return { chips = e.chips * n } end end)"),
    J("zorro_rojo", "Zorro Rojo", 1, 5,
      ["Ganas {C:money}$#1#{} por cada carta", "de " + PALO["Hearts"] + " descartada"],
      {"dollars": 1}, ["dollars"], 'KAS.discard_money(KAS.suit("Hearts"))', bp=False),
    J("gato_azul", "Gato Azul", 2, 7,
      ["Reactiva cada carta", "de " + PALO["Spades"] + " puntuada"], {"reps": 1}, [],
      'KAS.retrigger(KAS.suit("Spades"))'),
    J("simio_bufon", "Simio Bufón", 1, 4,
      [MULT % 1 + " por cada mano", "ya jugada esta ronda"], {"mult": 4}, ["mult"],
      "KAS.dyn(function(card, context, e) local n = G.GAME.current_round.hands_played "
      "if n > 0 then return { mult = e.mult * n } end end)"),
    J("leon_dorado", "León Dorado", 2, 7,
      ["Cada carta de {C:attention}figura{} puntuada", "da " + MULT % 1 + " y {C:money}$#2#{}"],
      {"mult": 3, "dollars": 1}, ["mult", "dollars"], "KAS.per_card(KAS.face)"),
    J("demonio_blanco", "Demonio Blanco", 3, 8,
      [XMULT % 1 + ";", PROB % (2, 3) + " de", "destruirse cada vez que {C:attention}descartas{}"],
      {"xmult": 3, "break_odds": 4}, ["xmult", "prob", "break_odds"],
      "KAS.combine(KAS.flat(), function(self, card, context) if context.pre_discard and not context.blueprint "
      "and pseudorandom('kas_demonio_blanco') < KAS.prob() / card.ability.extra.break_odds then "
      "KAS.destruir(card) return { message = localize('k_extinct_ex'), colour = G.C.RED } end end)",
      extra="eternal_compat = false"),

    # ---- Fila 2 ----
    J("bufon_real", "Bufón Real", 2, 7,
      ["Reactiva cada {C:attention}Rey{}", "puntuado"], {"reps": 1}, [], "KAS.retrigger(KAS.rank(13))"),
    crear("cientifico_loco", "Científico Loco", 1, 5,
          [PROB % (1, 2) + " de crear", "una carta de {C:planet}Planeta{} cada", "vez que usas un {C:tarot}Tarot{}"],
          "Planet", "KAS.T.consumable('Tarot')", odds=3),
    J("duende_sombrero", "Duende del Sombrero", 1, 4,
      ["Ganas {C:money}$#1#{} si la mano", "jugada contiene una {C:attention}Escalera{}"], {"dollars": 3}, ["dollars"],
      'KAS.hand("Straight")'),
    J("conejo_rosa", "Conejo Rosa", 1, 4,
      ["Cada {C:attention}2{} puntuado da " + MULT % 1, "por cada 2 de tu baraja completa"], {"mult": 1}, ["mult"],
      "KAS.per_card_fn(KAS.rank(2), function(c, context, e) "
      "return { mult = e.mult * KAS.contar(G.playing_cards, KAS.rank(2)) } end)"),
    J("bufon_llama", "Bufón de la Llama", 1, 5,
      ["Gana " + MULT % 1 + " cada vez", "que juegas un {C:attention}Color{}", ACTUAL_M % 2],
      {"gain": 5, "mult": 0}, ["gain", "mult"],
      "KAS.scale{ field = 'mult', on = KAS.T.hand_type('Flush') }"),
    rango("husky", "Husky", 1, 4, [7, 8], "{C:attention}7{} u {C:attention}8{}", {"chips": 20}),
    J("bufon_cortesano", "Bufón Cortesano", 1, 5,
      ["Cada {C:attention}Reina{} puntuada da " + MULT % 1, "por cada {C:attention}Rey{} que tengas en la mano"],
      {"mult": 6}, ["mult"],
      "KAS.per_card_fn(KAS.rank(12), function(c, context, e) local n = KAS.contar(G.hand.cards, KAS.rank(13)) "
      "if n > 0 then return { mult = e.mult * n } end end)"),
    J("gata_bufona", "Gata Bufona", 2, 6,
      ["{X:mult,C:white} +X#1# {} multi por cada carta", "de " + PALO["Hearts"] + " puntuada"],
      {"step": 0.2}, ["step"],
      "KAS.dyn(function(card, context, e) local n = KAS.contar(context.scoring_hand, KAS.suit('Hearts')) "
      "if n > 0 then return { xmult = 1 + e.step * n } end end)"),
    J("gato_suerte", "Gato de la Suerte", 2, 7,
      [PROB % (1, 2), "de dar " + XMULT % 3], {"odds": 7, "xmult": 7}, ["prob", "odds", "xmult"],
      'KAS.chance("kas_gato_suerte")'),
    J("planeta_azul", "Planeta Azul", 2, 6,
      [CHIPS % 1 + " por cada {C:attention}nivel{}", "de la mano jugada"], {"chips": 10}, ["chips"],
      "KAS.dyn(function(card, context, e) local h = G.GAME.hands[context.scoring_name] "
      "if h then return { chips = e.chips * h.level } end end)"),
    J("fantasma_mago", "Fantasma Mago", 1, 4,
      ["Gana " + MULT % 1 + " cada vez", "que usas una carta {C:spectral}Espectral{}", ACTUAL_M % 2],
      {"gain": 5, "mult": 0}, ["gain", "mult"],
      "KAS.scale{ field = 'mult', on = KAS.T.consumable('Spectral') }"),
    J("faro", "Faro", 2, 6,
      [XMULT % 1 + " si te quedan", "{C:attention}#2#{} o más cartas en la mano"], {"xmult": 1.5, "cards": 4},
      ["xmult", "cards"],
      "KAS.cond(function(card, context, e) return #G.hand.cards >= e.cards end)"),
    J("gato_brujo", "Gato Brujo", 2, 6,
      ["Al seleccionar la {C:attention}ciega{}, ganas", "{C:blue}+1{} mano o {C:red}+1{} descarte al azar"], {}, [],
      "function(self, card, context) if context.setting_blind then "
      "if pseudorandom('kas_gato_brujo') < 0.5 then ease_hands_played(1) return { message = '+1', colour = G.C.BLUE } end "
      "ease_discard(1) return { message = '+1', colour = G.C.RED } end end"),

    # ---- Fila 3 ----
    J("perro_calavera", "Perro Calavera", 1, 5,
      ["Gana " + CHIPS % 1 + " por cada", "carta {C:attention}descartada{}", ACTUAL_C % 2],
      {"gain": 3, "chips": 0}, ["gain", "chips"],
      "KAS.scale{ field = 'chips', on = KAS.T.discard }"),
    J("brujo_sombrio", "Brujo Sombrío", 2, 7,
      [XMULT % 1 + " si tienes al menos", "una carta de {C:tarot}Tarot{}"], {"xmult": 2}, ["xmult"],
      "KAS.cond(function() for _, c in ipairs(G.consumeables.cards) do "
      "if c.ability.set == 'Tarot' then return true end end return false end)"),
    J("conejo_blanco", "Conejo Blanco", 2, 6,
      ["{C:blue}+#1#{} mano por ronda,", "{C:red}-#2#{} descartes por ronda"], {"n": 1, "m": 2}, ["n", "m"],
      pasivo={"hands": 1, "discards": -2}, bp=False),
    crear("luna_violeta", "Luna Violeta", 1, 5,
          ["Si la mano contiene una {C:attention}Doble pareja{},", "crea una carta de {C:tarot}Tarot{}",
           "{C:inactive}(Debe haber espacio)"], "Tarot", 'KAS.T.hand_type("Two Pair")'),
    mano("oso_carmesi", "Oso Carmesí", 1, 4, "Full House", "Full", "mult", 20),
    retenida("boston_terrier", "Boston Terrier", 1, 4, "KAS.even", "carta {C:attention}par{}", "mult", 2),
    J("lingote_oro", "Lingote de Oro", 1, 6,
      ["Ganas {C:money}$#1#{} al final de la ronda", "si la superas con {C:attention}una sola{} mano"],
      {"dollars": 6}, ["dollars"],
      extra="calc_dollar_bonus = function(self, card) "
            "if G.GAME.current_round.hands_played == 1 then return card.ability.extra.dollars end end", bp=False),
    rango("cristal_rosa", "Cristal Rosa", 2, 6, [12], "{C:attention}Reina{}", {"xmult": 1.5}),
    J("cubo_hielo", "Cubo de Hielo", 1, 5,
      [CHIPS % 1 + ",", "pierde {C:chips}#2#{} fichas cada vez que descartas"],
      {"chips": 120, "loss": 10, "gain": -10}, ["chips", "loss"],
      "KAS.scale{ field = 'chips', on = KAS.T.pre_discard, destroy_at = 0 }"),
    J("zorro_paciente", "Zorro Paciente", 1, 5,
      ["Gana " + MULT % 1 + " al final", "de cada ronda", ACTUAL_M % 2],
      {"gain": 2, "mult": 0}, ["gain", "mult"],
      "KAS.scale{ field = 'mult', on = KAS.T.round_end }"),
    J("rey_demonio", "Rey Demonio", 3, 8,
      [XMULT % 1 + " por cada {C:attention}Rey{}", "en la mano puntuada"], {"xmult": 1.5}, ["xmult"],
      "KAS.dyn(function(card, context, e) local n = KAS.contar(context.scoring_hand, KAS.rank(13)) "
      "if n > 0 then return { xmult = e.xmult ^ n } end end)"),
    J("el_encapuchado", "El Encapuchado", 2, 6,
      [XMULT % 1 + " si todas las cartas puntuadas", "son {C:spades}Picas{} o {C:clubs}Tréboles{}"], {"xmult": 2}, ["xmult"],
      "KAS.cond(function(card, context) return KAS.contar(context.scoring_hand, KAS.suit('Spades', 'Clubs')) "
      "== #context.scoring_hand end)"),
    J("lampara_dorada", "Lámpara Dorada", 4, 20,
      [XMULT % 1, "Crea una carta {C:spectral}Espectral{}", "al seleccionar la {C:attention}ciega{}"],
      {"xmult": 2}, ["xmult"],
      'KAS.combine(KAS.flat(), KAS.create(KAS.T.blind, "Spectral"))'),

    # ---- Fila 4 ----
    J("lobo_violeta", "Lobo Violeta", 1, 4,
      [MULT % 1 + " si tienes", "{C:attention}#2#{} comodines o más"], {"mult": 10, "min": 3}, ["mult", "min"],
      "KAS.cond(function(card, context, e) return #G.jokers.cards >= e.min end)"),
    J("bufon_sol", "Bufón del Sol", 1, 5,
      ["Cada carta {C:hearts}roja{} puntuada", "da " + MULT % 1 + " y " + CHIPS % 2],
      {"mult": 2, "chips": 10}, ["mult", "chips"], 'KAS.per_card(KAS.suit("Hearts", "Diamonds"))'),
    rango("calavera_dorada", "Calavera Dorada", 2, 7, [14], "{C:attention}As{}", {"xmult": 1.5}),
    J("bufon_nocturno", "Bufón Nocturno", 1, 4,
      [MULT % 1 + " si la mano puntuada", "no tiene {C:attention}figuras{} ni {C:attention}Ases{}"], {"mult": 25}, ["mult"],
      "KAS.cond(function(card, context) return KAS.contar(context.scoring_hand, "
      "function(c) return c:is_face() or c:get_id() == 14 end) == 0 end)"),
    rango("duende_bufon", "Duende Bufón", 1, 4, [11, 12], "{C:attention}J{} o {C:attention}Reina{}", {"chips": 20}),
    J("llama_azul", "Llama Azul", 2, 7,
      ["Gana " + XMULT % 1 + " por cada carta", "de " + PALO["Spades"] + " puntuada", ACTUAL_X % 2],
      {"gain": 0.05, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = function(context) return context.before "
      "and KAS.contar(context.scoring_hand, KAS.suit('Spades')) end }"),
    J("dado_rojo", "Dado Rojo", 2, 6,
      [PROB % (1, 2), "de dar " + XMULT % 3], {"odds": 6, "xmult": 6}, ["prob", "odds", "xmult"],
      'KAS.chance("kas_dado_rojo")'),
    J("conde_vampiro", "Conde Vampiro", 3, 8,
      ["Gana " + XMULT % 1 + " por cada carta", "de " + PALO["Hearts"] + " puntuada", ACTUAL_X % 2],
      {"gain": 0.1, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = function(context) return context.before "
      "and KAS.contar(context.scoring_hand, KAS.suit('Hearts')) end }"),
    J("orbe_demoniaco", "Orbe Demoníaco", 2, 6,
      [XMULT % 1 + ", pierde {X:mult,C:white} X#2# {}", "por mano jugada"],
      {"xmult": 2, "loss": 0.1, "gain": -0.1}, ["xmult", "loss"],
      "KAS.scale{ field = 'xmult', on = KAS.T.hand_played, destroy_at = 1 }"),
    J("meteorito", "Meteorito", 2, 6,
      [CHIPS % 1 + " por cada {C:attention}nivel{}", "sumando todas tus manos de póker"], {"chips": 2}, ["chips"],
      "KAS.dyn(function(card, context, e) local n = 0 for _, h in pairs(G.GAME.hands) do n = n + h.level end "
      "return { chips = e.chips * n } end)"),
    J("calavera_bruja", "Calavera Bruja", 1, 4,
      [CHIPS % 1 + " por cada consumible", "usado en la partida"], {"chips": 5}, ["chips"],
      "KAS.dyn(function(card, context, e) local n = (G.GAME.consumeable_usage_total "
      "and G.GAME.consumeable_usage_total.all) or 0 if n > 0 then return { chips = e.chips * n } end end)"),
    J("dado_azul", "Dado Azul", 1, 4,
      ["Da entre {C:chips}+#1#{} y {C:chips}+#2#{}", "fichas al azar"], {"min": 10, "max": 100}, ["min", "max"],
      "KAS.dyn(function(card, context, e) return { chips = pseudorandom('kas_dado_azul', e.min, e.max) } end)"),
    J("mascara_dorada", "Máscara Dorada", 4, 20,
      ["Cada carta de {C:attention}figura{}", "puntuada da " + XMULT % 1], {"xmult": 1.5}, ["xmult"],
      "KAS.per_card(KAS.face)"),
]

assert len(COMODINES) == 52, len(COMODINES)
