"""Comodines de la hoja 2 (assets/fuente/hoja_comodines_2.webp): 13 columnas x 5 filas.

Mismo formato que tools/comodines.py; el orden es el de la hoja, fila a fila.
"""
from comodines import (ACTUAL_C, ACTUAL_M, ACTUAL_X, CHIPS, MULT, PALO, PROB, XMULT,
                       J, crear, mano, palo, rango, retenida)

COMODINES = [
    # ---- Fila 1 ----
    J("bufon_infernal", "Bufón Infernal", 3, 8,
      ["Gana " + XMULT % 1 + " por cada", "mano jugada en la partida", ACTUAL_X % 2],
      {"gain": 0.05, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = KAS.T.hand_played }"),
    crear("aprendiz_mago", "Aprendiz de Mago", 2, 6,
          ["Si la mano contiene un {C:attention}Full{},", "crea una carta de {C:tarot}Tarot{}",
           "{C:inactive}(Debe haber espacio)"], "Tarot", 'KAS.T.hand_type("Full House")'),
    retenida("espiritu_hielo", "Espíritu de Hielo", 1, 5, 'KAS.suit("Spades")',
             "carta de " + PALO["Spades"], "mult", 3),
    J("robot_dorado", "Robot Dorado", 2, 6,
      [XMULT % 1 + " si tienes", "{C:money}$#2#{} o más"], {"xmult": 1.5, "min": 20}, ["xmult", "min"],
      "KAS.cond(function(card, context, e) return G.GAME.dollars >= e.min end)"),
    J("cipres_esmeralda", "Ciprés Esmeralda", 1, 5,
      ["Si la mano contiene un {C:attention}Color{},", "cada carta puntuada da " + MULT % 1], {"mult": 3}, ["mult"],
      "KAS.per_card(KAS.jugada('Flush', 'Straight Flush', 'Flush House', 'Flush Five'))"),
    crear("galaxia_espiral", "Galaxia Espiral", 2, 6,
          ["Si la mano jugada es {C:attention}Carta alta{},", "crea una carta de {C:planet}Planeta{}",
           "{C:inactive}(Debe haber espacio)"], "Planet",
          "function(context) return context.before and context.scoring_name == 'High Card' end"),
    J("el_anciano", "El Anciano", 1, 5,
      [CHIPS % 1 + " por cada", "{C:attention}ronda{} de la partida"], {"chips": 5}, ["chips"],
      "KAS.dyn(function(card, context, e) return { chips = e.chips * G.GAME.round } end)"),
    palo("zorro_nocturno", "Zorro Nocturno", 1, 4, "Diamonds", "chips", 30),
    J("gato_esmoquin", "Gato de Esmoquin", 1, 4,
      ["Cada carta de " + PALO["Spades"] + " puntuada da", "el {C:attention}doble{} de su valor en {C:chips}fichas{}"],
      {}, [], "KAS.per_card_fn(KAS.suit('Spades'), function(c) return { chips = 2 * KAS.valor(c) } end)"),
    J("perro_santo", "Perro Santo", 2, 6,
      ["Ganas {C:money}$#1#{} si la mano puntuada", "tiene {C:attention}5{} cartas de " + PALO["Hearts"]],
      {"dollars": 5}, ["dollars"],
      "KAS.cond(function(card, context) return KAS.contar(context.scoring_hand, KAS.suit('Hearts')) >= 5 end)"),
    J("gato_murcielago", "Gato Murciélago", 2, 6,
      ["Gana " + MULT % 1 + " por cada carta", "de " + PALO["Spades"] + " puntuada", ACTUAL_M % 2],
      {"gain": 1, "mult": 0}, ["gain", "mult"],
      "KAS.scale{ field = 'mult', on = function(context) return context.before "
      "and KAS.contar(context.scoring_hand, KAS.suit('Spades')) end }"),
    J("estrella_azul", "Estrella Azul", 2, 7,
      ["Si la mano contiene un {C:attention}Color{},", "cada carta puntuada da " + XMULT % 1], {"xmult": 1.1}, ["xmult"],
      "KAS.per_card(KAS.jugada('Flush', 'Straight Flush', 'Flush House', 'Flush Five'))"),
    J("payaso_psicodelico", "Payaso Psicodélico", 2, 7,
      ["Da entre {X:mult,C:white} X#1# {} y {X:mult,C:white} X#2# {}", "multi al azar"],
      {"min": 1, "max": 3}, ["min", "max"],
      "KAS.dyn(function(card, context, e) local x = e.min + (e.max - e.min) * pseudorandom('kas_payaso_psicodelico') "
      "return { xmult = math.floor(x * 10 + 0.5) / 10 } end)"),

    # ---- Fila 2 ----
    J("sombra_encapuchada", "Sombra Encapuchada", 2, 6,
      [XMULT % 1 + " en la {C:attention}última mano{}", "si no te quedan {C:attention}descartes{}"], {"xmult": 2.5}, ["xmult"],
      "KAS.cond(function() return G.GAME.current_round.hands_left == 0 "
      "and G.GAME.current_round.discards_left == 0 end)"),
    J("payaso_mago", "Payaso Mago", 1, 5,
      [MULT % 1 + " por cada carta", "de {C:tarot}Tarot{} que tengas"], {"mult": 5}, ["mult"],
      "KAS.dyn(function(card, context, e) local n = 0 for _, c in ipairs(G.consumeables.cards) do "
      "if c.ability.set == 'Tarot' then n = n + 1 end end "
      "if n > 0 then return { mult = e.mult * n } end end)"),
    J("mascara_calabaza", "Máscara de Calabaza", 1, 4,
      [MULT % 1 + " si juegas", "exactamente {C:attention}#2#{} cartas"], {"mult": 13, "cards": 4}, ["mult", "cards"],
      "KAS.cond(function(card, context, e) return #context.full_hand == e.cards end)"),
    palo("bufon_carmesi", "Bufón Carmesí", 1, 4, "Hearts", "chips", 30),
    crear("runa_lunar", "Runa Lunar", 2, 6,
          [PROB % (1, 2) + " de crear", "una carta de {C:tarot}Tarot{} al", "seleccionar la {C:attention}ciega{}"],
          "Tarot", "KAS.T.blind", odds=2),
    J("pantera", "Pantera", 2, 7,
      ["Gana " + XMULT % 1 + " cada vez que", "juegas {C:attention}5{} cartas", ACTUAL_X % 2],
      {"gain": 0.1, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = function(context) return context.before and #context.full_hand == 5 end }"),
    mano("payaso_rockero", "Payaso Rockero", 1, 4, "Four of a Kind", "Póker", "mult", 20),
    J("rey_oscuro", "Rey Oscuro", 2, 7,
      ["Cada {C:attention}Rey{} puntuado da {C:money}$#1#{}", "por cada Rey que tengas en la mano"], {"dollars": 1},
      ["dollars"],
      "KAS.per_card_fn(KAS.rank(13), function(c, context, e) local n = KAS.contar(G.hand.cards, KAS.rank(13)) "
      "if n > 0 then return { dollars = e.dollars * n } end end)"),
    J("mascara_alada", "Máscara Alada", 2, 7,
      ["Reactiva cada carta", "de " + PALO["Diamonds"] + " puntuada"], {"reps": 1}, [],
      'KAS.retrigger(KAS.suit("Diamonds"))'),
    retenida("emperador", "Emperador", 3, 9, "KAS.face", "carta de {C:attention}figura{}", "xmult", 1.2),
    rango("idolo_dorado", "Ídolo Dorado", 2, 7, [14], "{C:attention}As{}", {"dollars": 2}),
    J("demonio_rojo", "Demonio Rojo", 1, 5,
      ["Gana " + MULT % 1 + " cada vez", "que juegas un {C:attention}Trío{}", ACTUAL_M % 2],
      {"gain": 3, "mult": 0}, ["gain", "mult"], "KAS.scale{ field = 'mult', on = KAS.T.hand_type('Three of a Kind') }"),
    J("ciclope", "Cíclope", 2, 6,
      [XMULT % 1 + " si juegas", "{C:attention}una sola{} carta"], {"xmult": 3}, ["xmult"],
      "KAS.cond(function(card, context) return #context.full_hand == 1 end)"),

    # ---- Fila 3 ----
    J("encapuchado_llameante", "Encapuchado Llameante", 1, 5,
      ["Gana " + MULT % 1 + " por cada carta", "de " + PALO["Hearts"] + " descartada", ACTUAL_M % 2],
      {"gain": 2, "mult": 0}, ["gain", "mult"],
      "KAS.scale{ field = 'mult', on = function(context) return context.discard "
      "and context.other_card:is_suit('Hearts') end }"),
    J("duende_naranja", "Duende Naranja", 1, 5,
      ["Ganas {C:money}$#1#{} por cada carta", "de " + PALO["Diamonds"] + " descartada"],
      {"dollars": 1}, ["dollars"], 'KAS.discard_money(KAS.suit("Diamonds"))', bp=False),
    J("espiritu_violeta", "Espíritu Violeta", 1, 3,
      ["Al {C:attention}venderlo{}, crea una", "carta de {C:planet}Planeta{}"], {}, [],
      'KAS.sell_create("Planet")', bp=False),
    J("fantasma_azul", "Fantasma Azul", 1, 4,
      [CHIPS % 1 + " por cada", "{C:attention}descarte{} usado esta ronda"], {"chips": 20}, ["chips"],
      "KAS.dyn(function(card, context, e) local n = G.GAME.current_round.discards_used "
      "if n > 0 then return { chips = e.chips * n } end end)"),
    J("cuchilla_cristal", "Cuchilla de Cristal", 2, 7,
      ["Gana " + XMULT % 1 + " cada vez", "que juegas un {C:attention}Color{}", ACTUAL_X % 2],
      {"gain": 0.2, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = KAS.T.hand_type('Flush') }"),
    J("bufon_dorado", "Bufón Dorado", 1, 6,
      ["Ganas {C:money}$#1#{} al final de la ronda por", "cada carta de {C:attention}Oro{} de tu baraja"],
      {"dollars": 2}, ["dollars"],
      extra="calc_dollar_bonus = function(self, card) local n = KAS.contar(G.playing_cards, KAS.mejora('m_gold')) "
            "if n > 0 then return n * card.ability.extra.dollars end end", bp=False),
    rango("caballero_oscuro", "Caballero Oscuro", 2, 6, [11], "{C:attention}J{}", {"xmult": 1.5}),
    rango("payaso_demonio", "Payaso Demonio", 1, 4, [4], "{C:attention}4{}", {"mult": 8}),
    crear("bruja", "Bruja", 2, 7,
          ["Crea una carta {C:spectral}Espectral{}", "al derrotar una {C:attention}ciega jefe{}",
           "{C:inactive}(Debe haber espacio)"], "Spectral", "KAS.T.boss"),
    rango("lince", "Lince", 1, 4, [9], "{C:attention}9{}", {"mult": 9}),
    J("cohete", "Cohete", 1, 5,
      ["Gana " + CHIPS % 1 + " por cada", "mano jugada", ACTUAL_C % 2],
      {"gain": 8, "chips": 0}, ["gain", "chips"],
      "KAS.scale{ field = 'chips', on = KAS.T.hand_played }"),
    crear("bufon_brujo", "Bufón Brujo", 2, 6,
          ["Crea una carta de {C:planet}Planeta{}", "al seleccionar la {C:attention}ciega{}",
           "{C:inactive}(Debe haber espacio)"], "Planet", "KAS.T.blind"),
    J("farol_naranja", "Farol Naranja", 1, 4,
      [MULT % 1 + " por cada carta", "que tengas en la {C:attention}mano{}"], {"mult": 2}, ["mult"],
      "KAS.dyn(function(card, context, e) if #G.hand.cards > 0 then "
      "return { mult = e.mult * #G.hand.cards } end end)"),

    # ---- Fila 4 ----
    J("payaso_fantasma", "Payaso Fantasma", 2, 6,
      [PROB % (1, 2), "de dar " + XMULT % 3], {"odds": 3, "xmult": 3}, ["prob", "odds", "xmult"],
      'KAS.chance("kas_payaso_fantasma")'),
    J("caliz_dorado", "Cáliz Dorado", 1, 5,
      ["Al final de la ronda ganas {C:money}$#1#{}", "por cada {C:attention}mano{} restante"],
      {"dollars": 1}, ["dollars"],
      extra="calc_dollar_bonus = function(self, card) local n = G.GAME.current_round.hands_left "
            "if n > 0 then return n * card.ability.extra.dollars end end", bp=False),
    J("hombre_misterioso", "Hombre Misterioso", 1, 4,
      [MULT % 1 + " si la mano", "jugada es {C:attention}Carta alta{}"], {"mult": 15}, ["mult"],
      "KAS.cond(function(card, context) return context.scoring_name == 'High Card' end)"),
    J("pulpo_mago", "Pulpo Mago", 2, 6,
      ["Reactiva cada {C:attention}8{}", "puntuado"], {"reps": 1}, [], "KAS.retrigger(KAS.rank(8))"),
    J("leon_solar", "León Solar", 2, 7,
      ["Cada carta de " + PALO["Diamonds"] + " puntuada", "da " + XMULT % 1], {"xmult": 1.2}, ["xmult"],
      'KAS.per_card(KAS.suit("Diamonds"))'),
    J("gato_saturno", "Gato de Saturno", 1, 5,
      [MULT % 1 + " si tienes al menos", "una carta de {C:planet}Planeta{}"], {"mult": 15}, ["mult"],
      "KAS.cond(function() for _, c in ipairs(G.consumeables.cards) do "
      "if c.ability.set == 'Planet' then return true end end return false end)"),
    J("sol_ardiente", "Sol Ardiente", 1, 5,
      [MULT % 1 + " en la", "{C:attention}primera mano{} de la ronda"], {"mult": 20}, ["mult"],
      "KAS.cond(KAS.first_hand)"),
    J("ojo_mosaico", "Ojo del Mosaico", 1, 5,
      [CHIPS % 1 + " por cada carta de", "{C:attention}figura{} en tu baraja completa"], {"chips": 3}, ["chips"],
      "KAS.dyn(function(card, context, e) local n = KAS.contar(G.playing_cards, KAS.face) "
      "if n > 0 then return { chips = e.chips * n } end end)"),
    J("bufon_colorido", "Bufón Colorido", 1, 3,
      [MULT % 1 + " y " + CHIPS % 2], {"mult": 4, "chips": 30}, ["mult", "chips"], "KAS.flat()"),
    J("rey_leon", "Rey León", 2, 7,
      [XMULT % 1 + " si la mano", "puntuada contiene un {C:attention}Rey{}"], {"xmult": 2}, ["xmult"],
      "KAS.cond(function(card, context) return KAS.contar(context.scoring_hand, KAS.rank(13)) > 0 end)"),
    J("calavera_maga", "Calavera Maga", 1, 5,
      ["Ganas {C:money}$#1#{} cada vez que", "usas una carta de {C:tarot}Tarot{}"], {"dollars": 2}, ["dollars"],
      "function(self, card, context) if KAS.T.consumable('Tarot')(context) then "
      "KAS.dinero(card, card.ability.extra.dollars) end end"),
    rango("esqueleto_mecanico", "Esqueleto Mecánico", 1, 4, [2, 3], "{C:attention}2{} o {C:attention}3{}",
          {"chips": 20, "mult": 2}),
    J("rey_de_los_bufones", "Rey de los Bufones", 4, 20,
      ["Cada carta de {C:attention}figura{} puntuada", "se reactiva una vez por cada", "{C:attention}Rey{} en la mano puntuada"],
      {}, [],
      "function(self, card, context) if context.repetition and context.cardarea == G.play "
      "and context.other_card:is_face() then local n = KAS.contar(context.scoring_hand, KAS.rank(13)) "
      "if n > 0 then return { repetitions = n } end end end"),

    # ---- Fila 5 ----
    rango("lince_marron", "Lince Marrón", 1, 4, [5], "{C:attention}5{}", {"mult": 5, "chips": 25}),
    mano("perro_lila", "Perro Lila", 2, 6, "Two Pair", "Doble pareja", "xmult", 1.5),
    J("hombre_lobo", "Hombre Lobo", 3, 8,
      ["Gana " + XMULT % 1 + " cada vez", "que juegas un {C:attention}Póker{}", ACTUAL_X % 2],
      {"gain": 1, "xmult": 1}, ["gain", "xmult"], "KAS.scale{ field = 'xmult', on = KAS.T.hand_type('Four of a Kind') }"),
    J("duende_verde", "Duende Verde", 1, 5,
      ["Ganas {C:money}$#1#{} si la mano", "jugada contiene una {C:attention}Pareja{}"], {"dollars": 1}, ["dollars"],
      'KAS.hand("Pair")'),
    J("bestia_sombria", "Bestia Sombría", 2, 6,
      ["{X:mult,C:white} +X#1# {} multi por cada", "espacio de {C:attention}consumible{} vacío"], {"step": 0.5}, ["step"],
      "KAS.dyn(function(card, context, e) local n = G.consumeables.config.card_limit - #G.consumeables.cards "
      "if n > 0 then return { xmult = 1 + e.step * n } end end)"),
    J("gato_bufon", "Gato Bufón", 2, 6,
      ["Cada carta de " + PALO["Clubs"] + " puntuada", "da {C:money}$#1#{}"],
      {"dollars": 1}, ["dollars"], 'KAS.per_card(KAS.suit("Clubs"))'),
    crear("sumo_sacerdote", "Sumo Sacerdote", 2, 7,
          ["Crea una carta de {C:tarot}Tarot{}", "cada vez que usas un {C:planet}Planeta{}",
           "{C:inactive}(Debe haber espacio)"], "Tarot", "KAS.T.consumable('Planet')"),
    J("rueda_fortuna", "Rueda de la Fortuna", 2, 6,
      [PROB % (1, 2) + " de", "ganar {C:money}$#3#{} al jugar una mano"],
      {"odds": 5, "dollars": 10}, ["prob", "odds", "dollars"], 'KAS.chance("kas_rueda_fortuna")'),
    J("calabaza_duende", "Calabaza Duende", 1, 5,
      [MULT % 1 + ",", "pierde {C:mult}#2#{} multi por mano jugada"],
      {"mult": 25, "loss": 1, "gain": -1}, ["mult", "loss"],
      "KAS.scale{ field = 'mult', on = KAS.T.hand_played, destroy_at = 0 }"),
    J("luna_partida", "Luna Partida", 2, 6,
      [XMULT % 1 + " si la mano puntuada", "tiene cartas {C:hearts}rojas{} y {C:spades}negras{}"],
      {"xmult": 1.5}, ["xmult"],
      "KAS.cond(function(card, context) "
      "return KAS.contar(context.scoring_hand, KAS.suit('Hearts', 'Diamonds')) > 0 "
      "and KAS.contar(context.scoring_hand, KAS.suit('Spades', 'Clubs')) > 0 end)"),
    J("esqueleto_dorado", "Esqueleto Dorado", 1, 5,
      ["Ganas {C:money}$#1#{} al final de la ronda", "si tienes menos de {C:money}$#2#{}"],
      {"dollars": 4, "max": 10}, ["dollars", "max"],
      extra="calc_dollar_bonus = function(self, card) local e = card.ability.extra "
            "if G.GAME.dollars < e.max then return e.dollars end end", bp=False),
    J("ojo_vacio", "Ojo del Vacío", 3, 8,
      ["Gana " + XMULT % 1 + " cada vez", "que usas una carta {C:spectral}Espectral{}", ACTUAL_X % 2],
      {"gain": 0.5, "xmult": 1}, ["gain", "xmult"],
      "KAS.scale{ field = 'xmult', on = KAS.T.consumable('Spectral') }"),
    J("totem_verde", "Tótem Verde", 4, 20,
      ["En la {C:attention}primera mano{} de la ronda:", XMULT % 1 + " y reactiva todas", "las cartas puntuadas"],
      {"xmult": 2, "reps": 1}, ["xmult"],
      "KAS.combine(KAS.retrigger(KAS.first_hand), KAS.cond(KAS.first_hand))"),
]

assert len(COMODINES) == 65, len(COMODINES)
